// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaPortuario.Data;

#nullable disable

namespace SistemaPortuario.Migrations
{
    [DbContext(typeof(SistemaPortuarioDbContext))]
    [Migration("20260514220628_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaPortuario.Models.CitacionEstiba", b =>
                {
                    b.Property<int>("IdCitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCitacion"));

                    b.Property<string>("DetalleOperativo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoCitacion")
                        .HasColumnType("int");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdCitacion");

                    b.HasIndex("Fecha");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstadoCitacion");

                    b.ToTable("CitacionEstiba", (string)null);
                });

            modelBuilder.Entity("SistemaPortuario.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Correo")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("NombreContacto")
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCliente");

                    b.HasIndex("Rut")
                        .IsUnique();

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("SistemaPortuario.Models.Cuadrilla", b =>
                {
                    b.Property<int>("IdCuadrilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuadrilla"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCuadrilla");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Cuadrilla", (string)null);
                });

            modelBuilder.Entity("SistemaPortuario.Models.CuadrillaPersonal", b =>
                {
                    b.Property<int>("IdCuadrillaPersonal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuadrillaPersonal"));

                    b.Property<DateOnly>("FechaDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaHasta")
                        .HasColumnType("date");

                    b.Property<int>("IdCuadrilla")
                        .HasColumnType("int");

                    b.Property<int>("IdPersonalEstiba")
                        .HasColumnType("int");

                    b.HasKey("IdCuadrillaPersonal");

                    b.HasIndex("IdCuadrilla");

                    b.HasIndex("IdPersonalEstiba");

                    b.ToTable("CuadrillaPersonal", null, t =>
                        {
                            t.HasCheckConstraint("CK_CuadrillaPersonal_Fechas", "[FechaHasta] IS NULL OR [FechaHasta] >= [FechaDesde]");
                        });
                });

            modelBuilder.Entity("SistemaPortuario.Models.DetalleCitacionEstiba", b =>
                {
                    b.Property<int>("IdDetalleCitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleCitacion"));

                    b.Property<bool?>("Asistencia")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoAltaBps")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<TimeOnly?>("HoraFinReal")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("HoraInicioReal")
                        .HasColumnType("time");

                    b.Property<decimal?>("HorasTrabajadas")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("IdCitacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdCuadrilla")
                        .HasColumnType("int");

                    b.Property<int?>("IdLiquidacion")
                        .HasColumnType("int");

                    b.Property<int>("IdPersonalEstiba")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdDetalleCitacion");

                    b.HasIndex("IdCuadrilla");

                    b.HasIndex("IdLiquidacion");

                    b.HasIndex("IdPersonalEstiba");

                    b.HasIndex("IdCitacion", "IdPersonalEstiba")
                        .IsUnique();

                    b.ToTable("DetalleCitacionEstiba", null, t =>
                        {
                            t.HasCheckConstraint("CK_DetalleCitacionEstiba_Horas", "[HorasTrabajadas] IS NULL OR [HorasTrabajadas] >= 0");
                        });
                });

            modelBuilder.Entity("SistemaPortuario.Models.DocumentoPdf", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumento"));

                    b.Property<DateTime>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IdOrdenServicio")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdDocumento");

                    b.HasIndex("IdOrdenServicio")
                        .IsUnique();

                    b.ToTable("DocumentoPdf", (string)null);
                });

            modelBuilder.Entity("SistemaPortuario.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoEmpresa")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("Rut")
                        .IsUnique();

                    b.ToTable("Empresa", (string)null);
                });

            modelBuilder.Entity("SistemaPortuario.Models.EstadoCitacion", b =>
                {
                    b.Property<int>("IdEstadoCitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoCitacion"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdEstadoCitacion");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadoCitacion", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstadoCitacion = 1,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            IdEstadoCitacion = 2,
                            Nombre = "Enviada"
                        },
                        new
                        {
                            IdEstadoCitacion = 3,
                            Nombre = "Confirmada"
                        },
                        new
                        {
                            IdEstadoCitacion = 4,
                            Nombre = "Completada"
                        },
                        new
                        {
                            IdEstadoCitacion = 5,
                            Nombre = "Cancelada"
                        });
                });

            modelBuilder.Entity("SistemaPortuario.Models.EstadoMantenimiento", b =>
                {
                    b.Property<int>("IdEstadoMantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoMantenimiento"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdEstadoMantenimiento");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadoMantenimiento", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstadoMantenimiento = 1,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            IdEstadoMantenimiento = 2,
                            Nombre = "Programado"
                        },
                        new
                        {
                            IdEstadoMantenimiento = 3,
                            Nombre = "EnProceso"
                        },
                        new
                        {
                            IdEstadoMantenimiento = 4,
                            Nombre = "Realizado"
                        },
                        new
                        {
                            IdEstadoMantenimiento = 5,
                            Nombre = "Cancelado"
                        });
                });

            modelBuilder.Entity("SistemaPortuario.Models.EstadoOrdenServicio", b =>
                {
                    b.Property<int>("IdEstadoOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoOrden"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdEstadoOrden");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadoOrdenServicio", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstadoOrden = 1,
                            Descripcion = "Orden creada y pendiente de asignacion o inicio.",
                            Nombre = "Solicitada"
                        },
                        new
                        {
                            IdEstadoOrden = 2,
                            Descripcion = "Orden asignada a operario y maquinaria.",
                            Nombre = "Asignada"
                        },
                        new
                        {
                            IdEstadoOrden = 3,
                            Descripcion = "Servicio en ejecucion.",
                            Nombre = "EnProceso"
                        },
                        new
                        {
                            IdEstadoOrden = 4,
                            Descripcion = "Finalizada por operario y pendiente de validacion.",
                            Nombre = "PendienteValidacion"
                        },
                        new
                        {
                            IdEstadoOrden = 5,
                            Descripcion = "Validada por encargado.",
                            Nombre = "Validada"
                        },
                        new
                        {
                            IdEstadoOrden = 6,
                            Descripcion = "PDF enviado al cliente.",
                            Nombre = "EnviadaCliente"
                        },
                        new
                        {
                            IdEstadoOrden = 7,
                            Descripcion = "Orden enviada o registrada en facturacion.",
                            Nombre = "Facturada"
                        },
                        new
                        {
                            IdEstadoOrden = 8,
                            Descripcion = "Orden cancelada.",
                            Nombre = "Cancelada"
                        });
                });

            modelBuilder.Entity("SistemaPortuario.Models.EstadoTarea", b =>
                {
                    b.Property<int>("IdEstadoTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoTarea"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdEstadoTarea");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadoTarea", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstadoTarea = 1,
                            Nombre = "Sin comenzar"
                        },
                        new
                        {
                            IdEstadoTarea = 2,
                            Nombre = "En proceso"
                        },
                        new
                        {
                            IdEstadoTarea = 3,
                            Nombre = "Listo"
                        },
                        new
                        {
                            IdEstadoTarea = 4,
                            Nombre = "Cancelada"
                        });
                });

            modelBuilder.Entity("SistemaPortuario.Models.EventoCalendario", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvento"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCreador")
                        .HasColumnType("int");

                    b.Property<int?>("IdTarea")
                        .HasColumnType("int");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("IdEvento");

                    b.HasIndex("IdCreador");

                    b.HasIndex("IdTarea");

                    b.HasIndex("FechaInicio", "FechaFin");

                    b.ToTable("EventoCalendario", null, t =>
                        {
                            t.HasCheckConstraint("CK_EventoCalendario_Fechas", "[FechaFin] IS NULL OR [FechaFin] >= [FechaInicio]");
                        });
                });

            modelBuilder.Entity("SistemaPortuario.Models.Facturacion", b =>
                {
                    b.Property<int>("IdFacturacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFacturacion"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdOrdenServicio")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReferenciaGSoft")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdFacturacion");

                    b.HasIndex("IdOrdenServicio")
                        .IsUnique();

                    b.ToTable("Facturacion", (string)null);
                });

            modelBuilder.Entity("SistemaPortuario.Models.LiquidacionEstiba", b =>
                {
                    b.Property<int>("IdLiquidacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLiquidacion"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly>("PeriodoDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodoHasta")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalHoras")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("IdLiquidacion");

                    b.ToTable("LiquidacionEstiba", null, t =>
                        {
                            t.HasCheckConstraint("CK_LiquidacionEstiba_Periodo", "[PeriodoHasta] >= [PeriodoDesde]");

                            t.HasCheckConstraint("CK_LiquidacionEstiba_TotalHoras", "[TotalHoras] >= 0");
                        });
                });

            modelBuilder.Entity("SistemaPortuario.Models.Mantenimiento", b =>
                {
                    b.Property<int>("IdMantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMantenimiento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly?>("FechaProgramada")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaRealizada")
                        .HasColumnType("date");

                    b.Property<decimal?>("HorasMaquinaAlMomento")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("IdEstadoMantenimiento")
                        .HasColumnType("int");

                    b.Property<int>("IdMaquinaria")
                        .HasColumnType("int");

                    b.Property<int?>("IdRegistroHorasOrigen")
                        .HasColumnType("int");

                    b.Property<int?>("IdResponsable")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoMantenimiento")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdMantenimiento");

                    b.HasIndex("IdEstadoMantenimiento");

                    b.HasIndex("IdMaquinaria");

                    b.HasIndex("IdRegistroHorasOrigen");

                    b.HasIndex("IdResponsable");

                    b.HasIndex("IdTipoMantenimiento");

                    b.ToTable("Mantenimiento", null, t =>
                        {
                            t.HasCheckConstraint("CK_Mantenimiento_Horas", "[HorasMaquinaAlMomento] IS NULL OR [HorasMaquinaAlMomento] >= 0");
                        });
                });

            modelBuilder.Entity("SistemaPortuario.Models.Maquinaria", b =>
                {
                    b.Property<int>("IdMaquinaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaquinaria"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("HorasAcumuladas")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoMaquinaria")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Matricula")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdMaquinaria");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdTipoMaquinaria");

                    b.ToTable("Maquinaria", null, t =>
                        {
                            t.HasCheckConstraint("CK_Maquinaria_HorasAcumuladas", "[HorasAcumuladas] >= 0");
                        });
                });

            modelBuilder.Entity("SistemaPortuario.Models.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCitacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdOrdenServicio")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("IdCitacion");

                    b.HasIndex("IdOrdenServicio");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Notificacion", null, t =>
                        {
                            t.HasCheckConstraint("CK_Notificacion_Origen", "[IdUsuario] IS NOT NULL OR [IdOrdenServicio] IS NOT NULL OR [IdCitacion] IS NOT NULL");

                            t.HasCheckConstraint("CK_Notificacion_Tipo", "[Tipo] IN ('Email', 'WhatsApp', 'SMS', 'Sistema')");
                        });
                });

            modelBuilder.Entity("SistemaPortuario.Models.OrdenServicio", b =>
                {
                    b.Property<int>("IdOrdenServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrdenServicio"));

                    b.Property<bool>("EnviadaCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("HoraFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraInicioEstimada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraInicioReal")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdEncargado")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoOrden")
                        .HasColumnType("int");

                    b.Property<int>("IdMaquinariaAsignada")
                        .HasColumnType("int");

                    b.Property<int?>("IdMaquinariaFacturada")
                        .HasColumnType("int");

                    b.Property<int>("IdOperario")
                        .HasColumnType("int");

                    b.Property<string>("LugarServicio")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("PrecargadaGSoft")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("RequiereFirmaCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TrabajoARealizar")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdOrdenServicio");

                    b.HasIndex("FechaSolicitud");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdEncargado");

                    b.HasIndex("IdEstadoOrden");

                    b.HasIndex("IdMaquinariaAsignada");

                    b.HasIndex("IdMaquinariaFacturada");

                    b.HasIndex("IdOperario");

                    b.ToTable("OrdenServicio", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrdenServicio_Horas", "[HoraFinalizacion] IS NULL OR [HoraInicioReal] IS NULL OR [HoraFinalizacion] >= [HoraInicioReal]");
                        });
                });

            modelBuilder.Entity("SistemaPortuario.Models.PersonalEstiba", b =>
                {
                    b.Property<int>("IdPersonalEstiba")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersonalEstiba"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPersonalEstiba");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("PersonalEstiba", (string)null);
                });

            modelBuilder.Entity("SistemaPortuario.Models.RegistroHorasMaquinaria", b =>
                {
                    b.Property<int>("IdRegistroHoras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegistroHoras"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("HorasTrabajadas")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("IdMaquinaria")
                        .HasColumnType("int");

                    b.Property<int?>("IdOrdenServicio")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdRegistroHoras");

                    b.HasIndex("IdOrdenServicio");

                    b.HasIndex("IdMaquinaria", "Fecha");

                    b.ToTable("RegistroHorasMaquinaria", null, t =>
                        {
                            t.HasCheckConstraint("CK_RegistroHorasMaquinaria_Horas", "[HorasTrabajadas] > 0");
                        });
                });

            modelBuilder.Entity("SistemaPortuario.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            Nombre = "Encargado"
                        },
                        new
                        {
                            IdRol = 3,
                            Nombre = "Operario"
                        },
                        new
                        {
                            IdRol = 4,
                            Nombre = "Oficina"
                        });
                });

            modelBuilder.Entity("SistemaPortuario.Models.TareaAdministrativa", b =>
                {
                    b.Property<int>("IdTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarea"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAsignado")
                        .HasColumnType("int");

                    b.Property<int>("IdCreador")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoTarea")
                        .HasColumnType("int");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Media");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("IdTarea");

                    b.HasIndex("IdCreador");

                    b.HasIndex("IdEstadoTarea");

                    b.HasIndex("IdAsignado", "IdEstadoTarea");

                    b.ToTable("TareaAdministrativa", null, t =>
                        {
                            t.HasCheckConstraint("CK_TareaAdministrativa_Prioridad", "[Prioridad] IN ('Baja', 'Media', 'Alta', 'Urgente')");
                        });
                });

            modelBuilder.Entity("SistemaPortuario.Models.TipoMantenimiento", b =>
                {
                    b.Property<int>("IdTipoMantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoMantenimiento"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("UmbralHoras")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdTipoMantenimiento");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoMantenimiento", null, t =>
                        {
                            t.HasCheckConstraint("CK_TipoMantenimiento_UmbralHoras", "[UmbralHoras] IS NULL OR [UmbralHoras] > 0");
                        });
                });

            modelBuilder.Entity("SistemaPortuario.Models.TipoMaquinaria", b =>
                {
                    b.Property<int>("IdTipoMaquinaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoMaquinaria"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdTipoMaquinaria");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoMaquinaria", (string)null);
                });

            modelBuilder.Entity("SistemaPortuario.Models.Trazabilidad", b =>
                {
                    b.Property<long>("IdTrazabilidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdTrazabilidad"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatosPrevios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("IdRegistroAfectado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdTrazabilidad");

                    b.HasIndex("Entidad", "IdRegistroAfectado");

                    b.HasIndex("IdUsuario", "Fecha");

                    b.ToTable("Trazabilidad", (string)null);
                });

            modelBuilder.Entity("SistemaPortuario.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("SistemaPortuario.Models.CitacionEstiba", b =>
                {
                    b.HasOne("SistemaPortuario.Models.Cliente", "Cliente")
                        .WithMany("CitacionesEstiba")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPortuario.Models.EstadoCitacion", "EstadoCitacion")
                        .WithMany("Citaciones")
                        .HasForeignKey("IdEstadoCitacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("EstadoCitacion");
                });

            modelBuilder.Entity("SistemaPortuario.Models.CuadrillaPersonal", b =>
                {
                    b.HasOne("SistemaPortuario.Models.Cuadrilla", "Cuadrilla")
                        .WithMany("Personal")
                        .HasForeignKey("IdCuadrilla")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPortuario.Models.PersonalEstiba", "PersonalEstiba")
                        .WithMany("CuadrillasPersonal")
                        .HasForeignKey("IdPersonalEstiba")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuadrilla");

                    b.Navigation("PersonalEstiba");
                });

            modelBuilder.Entity("SistemaPortuario.Models.DetalleCitacionEstiba", b =>
                {
                    b.HasOne("SistemaPortuario.Models.CitacionEstiba", "Citacion")
                        .WithMany("Detalles")
                        .HasForeignKey("IdCitacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPortuario.Models.Cuadrilla", "Cuadrilla")
                        .WithMany("DetallesCitacion")
                        .HasForeignKey("IdCuadrilla")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPortuario.Models.LiquidacionEstiba", "Liquidacion")
                        .WithMany("DetallesCitacion")
                        .HasForeignKey("IdLiquidacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPortuario.Models.PersonalEstiba", "PersonalEstiba")
                        .WithMany("DetallesCitacion")
                        .HasForeignKey("IdPersonalEstiba")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Citacion");

                    b.Navigation("Cuadrilla");

                    b.Navigation("Liquidacion");

                    b.Navigation("PersonalEstiba");
                });

            modelBuilder.Entity("SistemaPortuario.Models.DocumentoPdf", b =>
                {
                    b.HasOne("SistemaPortuario.Models.OrdenServicio", "OrdenServicio")
                        .WithOne("DocumentoPdf")
                        .HasForeignKey("SistemaPortuario.Models.DocumentoPdf", "IdOrdenServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("SistemaPortuario.Models.EventoCalendario", b =>
                {
                    b.HasOne("SistemaPortuario.Models.Usuario", "Creador")
                        .WithMany("EventosCreados")
                        .HasForeignKey("IdCreador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPortuario.Models.TareaAdministrativa", "Tarea")
                        .WithMany("Eventos")
                        .HasForeignKey("IdTarea")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creador");

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("SistemaPortuario.Models.Facturacion", b =>
                {
                    b.HasOne("SistemaPortuario.Models.OrdenServicio", "OrdenServicio")
                        .WithOne("Facturacion")
                        .HasForeignKey("SistemaPortuario.Models.Facturacion", "IdOrdenServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("SistemaPortuario.Models.Mantenimiento", b =>
                {
                    b.HasOne("SistemaPortuario.Models.EstadoMantenimiento", "EstadoMantenimiento")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("IdEstadoMantenimiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPortuario.Models.Maquinaria", "Maquinaria")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("IdMaquinaria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPortuario.Models.RegistroHorasMaquinaria", "RegistroHorasOrigen")
                        .WithMany("MantenimientosOriginados")
                        .HasForeignKey("IdRegistroHorasOrigen")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPortuario.Models.Usuario", "Responsable")
                        .WithMany("MantenimientosResponsable")
                        .HasForeignKey("IdResponsable")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPortuario.Models.TipoMantenimiento", "TipoMantenimiento")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("IdTipoMantenimiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoMantenimiento");

                    b.Navigation("Maquinaria");

                    b.Navigation("RegistroHorasOrigen");

                    b.Navigation("Responsable");

                    b.Navigation("TipoMantenimiento");
                });

            modelBuilder.Entity("SistemaPortuario.Models.Maquinaria", b =>
                {
                    b.HasOne("SistemaPortuario.Models.Empresa", "Empresa")
                        .WithMany("Maquinarias")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPortuario.Models.TipoMaquinaria", "TipoMaquinaria")
                        .WithMany("Maquinarias")
                        .HasForeignKey("IdTipoMaquinaria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("TipoMaquinaria");
                });

            modelBuilder.Entity("SistemaPortuario.Models.Notificacion", b =>
                {
                    b.HasOne("SistemaPortuario.Models.CitacionEstiba", "Citacion")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdCitacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPortuario.Models.OrdenServicio", "OrdenServicio")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdOrdenServicio")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPortuario.Models.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Citacion");

                    b.Navigation("OrdenServicio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaPortuario.Models.OrdenServicio", b =>
                {
                    b.HasOne("SistemaPortuario.Models.Cliente", "Cliente")
                        .WithMany("OrdenesServicio")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPortuario.Models.Empresa", "Empresa")
                        .WithMany("OrdenesServicio")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPortuario.Models.Usuario", "Encargado")
                        .WithMany("OrdenesComoEncargado")
                        .HasForeignKey("IdEncargado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPortuario.Models.EstadoOrdenServicio", "EstadoOrden")
                        .WithMany("OrdenesServicio")
                        .HasForeignKey("IdEstadoOrden")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPortuario.Models.Maquinaria", "MaquinariaAsignada")
                        .WithMany("OrdenesAsignadas")
                        .HasForeignKey("IdMaquinariaAsignada")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPortuario.Models.Maquinaria", "MaquinariaFacturada")
                        .WithMany("OrdenesFacturadas")
                        .HasForeignKey("IdMaquinariaFacturada")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaPortuario.Models.Usuario", "Operario")
                        .WithMany("OrdenesComoOperario")
                        .HasForeignKey("IdOperario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");

                    b.Navigation("Encargado");

                    b.Navigation("EstadoOrden");

                    b.Navigation("MaquinariaAsignada");

                    b.Navigation("MaquinariaFacturada");

                    b.Navigation("Operario");
                });

            modelBuilder.Entity("SistemaPortuario.Models.RegistroHorasMaquinaria", b =>
                {
                    b.HasOne("SistemaPortuario.Models.Maquinaria", "Maquinaria")
                        .WithMany("RegistrosHoras")
                        .HasForeignKey("IdMaquinaria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPortuario.Models.OrdenServicio", "OrdenServicio")
                        .WithMany("RegistrosHorasMaquinaria")
                        .HasForeignKey("IdOrdenServicio")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Maquinaria");

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("SistemaPortuario.Models.TareaAdministrativa", b =>
                {
                    b.HasOne("SistemaPortuario.Models.Usuario", "Asignado")
                        .WithMany("TareasAsignadas")
                        .HasForeignKey("IdAsignado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPortuario.Models.Usuario", "Creador")
                        .WithMany("TareasCreadas")
                        .HasForeignKey("IdCreador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPortuario.Models.EstadoTarea", "EstadoTarea")
                        .WithMany("Tareas")
                        .HasForeignKey("IdEstadoTarea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asignado");

                    b.Navigation("Creador");

                    b.Navigation("EstadoTarea");
                });

            modelBuilder.Entity("SistemaPortuario.Models.Trazabilidad", b =>
                {
                    b.HasOne("SistemaPortuario.Models.Usuario", "Usuario")
                        .WithMany("Trazabilidades")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaPortuario.Models.Usuario", b =>
                {
                    b.HasOne("SistemaPortuario.Models.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPortuario.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaPortuario.Models.CitacionEstiba", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("SistemaPortuario.Models.Cliente", b =>
                {
                    b.Navigation("CitacionesEstiba");

                    b.Navigation("OrdenesServicio");
                });

            modelBuilder.Entity("SistemaPortuario.Models.Cuadrilla", b =>
                {
                    b.Navigation("DetallesCitacion");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("SistemaPortuario.Models.Empresa", b =>
                {
                    b.Navigation("Maquinarias");

                    b.Navigation("OrdenesServicio");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaPortuario.Models.EstadoCitacion", b =>
                {
                    b.Navigation("Citaciones");
                });

            modelBuilder.Entity("SistemaPortuario.Models.EstadoMantenimiento", b =>
                {
                    b.Navigation("Mantenimientos");
                });

            modelBuilder.Entity("SistemaPortuario.Models.EstadoOrdenServicio", b =>
                {
                    b.Navigation("OrdenesServicio");
                });

            modelBuilder.Entity("SistemaPortuario.Models.EstadoTarea", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("SistemaPortuario.Models.LiquidacionEstiba", b =>
                {
                    b.Navigation("DetallesCitacion");
                });

            modelBuilder.Entity("SistemaPortuario.Models.Maquinaria", b =>
                {
                    b.Navigation("Mantenimientos");

                    b.Navigation("OrdenesAsignadas");

                    b.Navigation("OrdenesFacturadas");

                    b.Navigation("RegistrosHoras");
                });

            modelBuilder.Entity("SistemaPortuario.Models.OrdenServicio", b =>
                {
                    b.Navigation("DocumentoPdf");

                    b.Navigation("Facturacion");

                    b.Navigation("Notificaciones");

                    b.Navigation("RegistrosHorasMaquinaria");
                });

            modelBuilder.Entity("SistemaPortuario.Models.PersonalEstiba", b =>
                {
                    b.Navigation("CuadrillasPersonal");

                    b.Navigation("DetallesCitacion");
                });

            modelBuilder.Entity("SistemaPortuario.Models.RegistroHorasMaquinaria", b =>
                {
                    b.Navigation("MantenimientosOriginados");
                });

            modelBuilder.Entity("SistemaPortuario.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaPortuario.Models.TareaAdministrativa", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("SistemaPortuario.Models.TipoMantenimiento", b =>
                {
                    b.Navigation("Mantenimientos");
                });

            modelBuilder.Entity("SistemaPortuario.Models.TipoMaquinaria", b =>
                {
                    b.Navigation("Maquinarias");
                });

            modelBuilder.Entity("SistemaPortuario.Models.Usuario", b =>
                {
                    b.Navigation("EventosCreados");

                    b.Navigation("MantenimientosResponsable");

                    b.Navigation("Notificaciones");

                    b.Navigation("OrdenesComoEncargado");

                    b.Navigation("OrdenesComoOperario");

                    b.Navigation("TareasAsignadas");

                    b.Navigation("TareasCreadas");

                    b.Navigation("Trazabilidades");
                });
#pragma warning restore 612, 618
        }
    }
}
